#!/usr/bin/env fish
set os (uname -s)
set class (yadm config local.class)

# --- Tools ---

if not type -q mise
    curl https://mise.run | sh
end

~/.local/bin/mise activate fish | source
mise install

# --- Platform packages ---

if test $os = Darwin
    brew bundle --global
else if test -f /etc/arch-release
    sudo pacman -S --needed - <~/.config/packages/pkglist
end

# --- Tmux plugins ---

# Catppuccin (manual install required for cyberdream theme - avoids name conflicts)
if not test -d ~/.config/tmux/plugins/catppuccin/tmux/.git
    git clone --depth 1 https://github.com/catppuccin/tmux ~/.config/tmux/plugins/catppuccin/tmux
end

# Cyberdream theme for catppuccin tmux
set -l cyberdream ~/.config/tmux/plugins/catppuccin/tmux/themes/catppuccin_cyberdream_tmux.conf
if not test -f $cyberdream
    curl -fsSL "https://raw.githubusercontent.com/scottmckendry/cyberdream.nvim/main/extras/tmux/cyberdream.conf" -o $cyberdream
end

# --- Alternates ---

yadm alt
