[tools]
1password = "latest"
1password-cli = "latest"
ansible = "latest"
codex = "latest"
direnv = "latest"
eza = "latest"
ghq = "latest"
github-cli = "latest"
go = "latest"
golangci-lint = "latest"
neovim = "latest"
node = "latest"
pipx = "latest"
python = "latest"
rust = "latest"
television = "latest"
tmux = "latest"
usage = "latest"
uv = "latest"
zoxide = "latest"
